# Generated by Django 4.2.4 on 2023-08-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=100)),
                ('Isbn', models.CharField(max_length=13)),
                ('Publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
